ALTER TYPE "QueryStatus" ADD VALUE IF NOT EXISTS 'ASSIGNED';
ALTER TYPE "QueryStatus" ADD VALUE IF NOT EXISTS 'AUTO_ESCALATED';
ALTER TYPE "QueryStatus" ADD VALUE IF NOT EXISTS 'HOD_ESCALATED';
ALTER TYPE "QueryStatus" ADD VALUE IF NOT EXISTS 'FORWARDED_TO_STAFF';
