"use client";
import { useState, useTransition } from "react";
import { forwardFromHod, forwardToHod, sendReply, generateAiDraft } from "@/app/(user)/staff/queries/[id]/actions";
type Recipient = { id: string; name: string | null; role: string };
export default function QueryHandlingActions({ queryId, recipients, isHod, disabled = false }: { queryId: string; aiDraftReply: string | null; recipients: Recipient[]; isHod: boolean; disabled?: boolean }) {
  const [mode, setMode] = useState<"resolve" | "forward" | null>(null);
  const [draft, setDraft] = useState("");
  const [pending, start] = useTransition();
  const forward = isHod ? forwardFromHod : forwardToHod;
  const generate = (action: "resolve" | "forward") => start(async () => { try { setDraft(await generateAiDraft(queryId, action)); } catch (error) { window.alert(error instanceof Error ? error.message : "Could not generate AI draft."); } });
  return <><div className="query-actions-bar"><button type="button" className="btn btn-primary" disabled={disabled} title={disabled ? "Actions unavailable while on leave" : undefined} onClick={() => { setDraft(""); setMode("resolve"); }}>Resolve</button><button type="button" className="btn btn-secondary" disabled={disabled} title={disabled ? "Actions unavailable while on leave" : undefined} onClick={() => { setDraft(""); setMode("forward"); }}>Forward</button></div>{mode && !disabled && <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && setMode(null)}><section className="modal card" role="dialog" aria-modal="true"><div className="modal-header"><h2 className="card-title">{mode === "resolve" ? "Resolve query" : "Forward query"}</h2><button type="button" className="btn btn-ghost btn-sm" onClick={() => setMode(null)}>×</button></div>{mode === "resolve" ? <form action={sendReply.bind(null, queryId)} onSubmit={() => setMode(null)}><textarea name="body" className="field-textarea" rows={7} required value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Write a reply to the student." /><input type="hidden" name="status" value="RESOLVED" /><div className="modal-actions"><button type="button" className="btn btn-outline-brand" onClick={() => generate("resolve")} disabled={pending}>{pending ? "Generating…" : "Generate AI Draft"}</button><button type="submit" className="btn btn-primary">Submit and resolve</button></div></form> : <form action={forward.bind(null, queryId)} onSubmit={() => setMode(null)}>{isHod && <select name="assignedToId" className="field-select" required><option value="">Select staff or HOD</option>{recipients.map((recipient) => <option key={recipient.id} value={recipient.id}>{recipient.name ?? "Unnamed"} ({recipient.role})</option>)}</select>}<textarea name="body" className="field-textarea" rows={7} required value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Explain why this query is being forwarded." /><div className="modal-actions"><button type="button" className="btn btn-outline-brand" onClick={() => generate("forward")} disabled={pending}>{pending ? "Generating…" : "Generate AI Response"}</button><button type="submit" className="btn btn-primary">Forward query</button></div></form>}</section></div>}</>;
}
