"use client";

import { useState } from "react";
import { signIn } from "next-auth/react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, FieldDescription, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import SocialAuthButtons from "@/components/SocialAuthButtons";

export function SignupForm({ className, ...props }: React.ComponentProps<"div">) {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (password !== confirm) { setError("Passwords do not match."); return; } setPending(true); const response = await fetch("/api/auth/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, email, password }) }); const data = await response.json(); if (!response.ok) { setError(data.error ?? "Could not create your account."); setPending(false); return; } const result = await signIn("credentials", { email, password, redirect: false, callbackUrl: "/dashboard" }); if (result?.error) setError("Account created, but sign-in failed."); else window.location.href = "/dashboard"; setPending(false); }
  return <div className={className} {...props}><Card className="auth-shadcn-card"><CardHeader><p className="auth-kicker">SMART QUERY HUB</p><CardTitle>Create an account</CardTitle><CardDescription>Choose a provider or use your email to get started.</CardDescription></CardHeader><CardContent><SocialAuthButtons action="Sign up" /><div className="divider-text">or create an account with email</div><form onSubmit={submit}>{error && <div className="auth-error" role="alert">{error}</div>}<FieldGroup><Field><FieldLabel htmlFor="signup-name">Full name</FieldLabel><Input id="signup-name" value={name} onChange={e => setName(e.target.value)} placeholder="Your full name" autoComplete="name" required /></Field><Field><FieldLabel htmlFor="signup-email">Email address</FieldLabel><Input id="signup-email" type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@vu.edu.pk" autoComplete="email" required /></Field><Field><FieldLabel htmlFor="signup-password">Password</FieldLabel><Input id="signup-password" type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="At least 8 characters" minLength={8} autoComplete="new-password" required /><FieldDescription>Use at least 8 characters.</FieldDescription></Field><Field><FieldLabel htmlFor="signup-confirm-password">Confirm password</FieldLabel><Input id="signup-confirm-password" type="password" value={confirm} onChange={e => setConfirm(e.target.value)} placeholder="Repeat your password" minLength={8} autoComplete="new-password" required /></Field><Button className="btn btn-primary w-full" type="submit" disabled={pending}>{pending ? "Creating account…" : "Create account"}</Button></FieldGroup></form><FieldDescription className="auth-switch">Already have an account? <a href="/login">Sign in</a></FieldDescription></CardContent></Card></div>;
}
